name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare environment
      run: sudo gem install bundler -v 1.17.2 && sudo apt-get install python3-setuptools

    - name: Install dependencies
      run: make deps

    - name: Build project
      run: make build web-build

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test
      env:
        CI: true
